export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_ITEM_DETAIL = "FETCH_ITEM_DETAIL";

export const FILTER_CATEGORIES = "FILTER_CATEGORIES";
export const POST_CATEGORY = "POST_CATEGORY";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_BRANDS = "FETCH_BRANDS";
export const FETCH_VARIATONS = "FETCH_VARIATONS";

export const FETCH_PROFILE = "FETCH_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const POST_ADDRESS = "POST_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";

export const UPDATE_USER = "UPDATE_USER";
