export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FILTER_CATEGORIES = "FILTER_CATEGORIES";
export const POST_CATEGORY = "POST_CATEGORY";
export const FETCH_PROFILE = "FETCH_PROFILE";
